### ISSUE TITLE
Newline at end of read

### ISSUE THREAD

**Issue by BD103** [darkdarcool/DS_Shell#4]
Please print a new line at the end of a read statement (cat).

**Comment by darkdarcool** [comment]
will fix. I didn't think anyone would use this, ill fix it tomorrow.

**Comment by darkdarcool** [comment]
to fix it now, for every file you read, put an empty new line, like at the end of a file just press `enter` and have on empty line

**Comment by BD103** [comment]
Ok :P

**Comment by darkdarcool** [comment]
Fixed
